"""third Migration

Revision ID: 653b6bf9de29
Revises: 539a6014949e
Create Date: 2018-10-21 17:27:33.999023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653b6bf9de29'
down_revision = '539a6014949e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_data', sa.String(length=255), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
